''' Solution for task 2'''

from datetime import datetime
import commun


def task2_solution():
    """ Find out in which day the most revenue for users
        who ordered via a mobile phone was created """

    # sql query for task 2
    task2_query = ''' SELECT tr.datetime , tr.revenue , tr.visitor_id
                      FROM Transactions tr
                      INNER JOIN devices dv ON dv.id = tr.device_type
                      WHERE dv.device_name = 'Mobile Phone'
                      ORDER BY revenue DESC'''

    # execute the sql query and print the result
    result = commun.connect_and_execute_query(task2_query)

    if len(result) > 1 and len(result[0]) > 1:
        date_time, revenue, visitor_id = result[0][0]
        date = datetime.strptime(date_time, "%Y-%m-%d %H:%M:%S")

        print(f'The day with the most revenue is {date.strftime("%Y-%m-%d")} '
                f'generated by the visitor with the ID {visitor_id} '
                f'using a Mobile Phone with the revenue {revenue} ')
    else:
        print("No result was found in the database")


if __name__ == '__main__':
    task2_solution()
