import sqlite3
from datetime import datetime

def task2():
    ''' On which day the most revenue for users who ordered via a mobile phone was created 
    '''
    connection = sqlite3.connect('transactions.db')
    cursor = connection.cursor()
    
    

    task2Request = '''SELECT Transactions.datetime , Transactions.revenue , Transactions.visitor_id
                      FROM Transactions
                      INNER JOIN devices ON devices.id = Transactions.device_type
                      WHERE devices.device_name = 'Mobile Phone'
                      ORDER BY revenue DESC''' 
                       
    cursor.execute(task2Request)

    date_time, revenue, visitor_id = cursor.fetchone()
    date = datetime.strptime(date_time, "%Y-%m-%d %H:%M:%S")
    
    print(
        f'The day with the most revenue is {date.strftime("%Y-%m-%d")} ' 
        f'generated by the visitor with the ID {visitor_id} using a Mobile Phone '
        f'with the revenue {revenue} '
        )
    
    connection.close()

if __name__ == '__main__':
    task2()
